// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type ClientScope struct {
	ClientID  string         `json:"client_id"`
	ScopeID   int32          `json:"scope_id"`
	GrantedAt time.Time      `json:"granted_at"`
	GrantedBy sql.NullString `json:"granted_by"`
}

type InternalClient struct {
	ClientID         string         `json:"client_id"`
	ClientSecretHash string         `json:"client_secret_hash"`
	ServiceName      string         `json:"service_name"`
	Description      sql.NullString `json:"description"`
	IsActive         sql.NullBool   `json:"is_active"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
}

type Scope struct {
	ID          int32          `json:"id"`
	ScopeName   string         `json:"scope_name"`
	Description sql.NullString `json:"description"`
	IsActive    sql.NullBool   `json:"is_active"`
	CreatedAt   time.Time      `json:"created_at"`
}

type ServiceAccessLog struct {
	ID             int32          `json:"id"`
	ClientID       string         `json:"client_id"`
	Endpoint       string         `json:"endpoint"`
	Method         string         `json:"method"`
	StatusCode     int32          `json:"status_code"`
	ResponseTimeMs sql.NullInt32  `json:"response_time_ms"`
	IpAddress      pqtype.Inet    `json:"ip_address"`
	UserAgent      sql.NullString `json:"user_agent"`
	RequestBody    sql.NullString `json:"request_body"`
	ResponseBody   sql.NullString `json:"response_body"`
	CreatedAt      time.Time      `json:"created_at"`
}

type ServiceToken struct {
	ID        int32        `json:"id"`
	ClientID  string       `json:"client_id"`
	TokenHash string       `json:"token_hash"`
	Scopes    []string     `json:"scopes"`
	ExpiresAt time.Time    `json:"expires_at"`
	IsRevoked sql.NullBool `json:"is_revoked"`
	CreatedAt time.Time    `json:"created_at"`
}

type Tenant struct {
	ID               string    `json:"id"`
	Name             string    `json:"name"`
	ApiSecretKeyHash string    `json:"api_secret_key_hash"`
	ApiPublicKey     string    `json:"api_public_key"`
	CreatedAt        time.Time `json:"created_at"`
}

type User struct {
	ID             string                `json:"id"`
	TenantID       string                `json:"tenant_id"`
	Email          string                `json:"email"`
	HashedPassword sql.NullString        `json:"hashed_password"`
	Profile        pqtype.NullRawMessage `json:"profile"`
	CreatedAt      time.Time             `json:"created_at"`
}

type UserRefreshToken struct {
	ID        int32          `json:"id"`
	UserID    string         `json:"user_id"`
	TokenHash string         `json:"token_hash"`
	ExpiresAt time.Time      `json:"expires_at"`
	CreatedAt time.Time      `json:"created_at"`
	ClientIp  sql.NullString `json:"client_ip"`
	UserAgent sql.NullString `json:"user_agent"`
}
