// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	ActivateInternalClient(ctx context.Context, clientID string) error
	CheckClientHasScope(ctx context.Context, arg CheckClientHasScopeParams) (bool, error)
	CleanupExpiredTokens(ctx context.Context) error
	CreateInternalClient(ctx context.Context, arg CreateInternalClientParams) (InternalClient, error)
	// 用户Refresh Token表
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateScope(ctx context.Context, arg CreateScopeParams) (Scope, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateInternalClient(ctx context.Context, clientID string) error
	DeactivateScope(ctx context.Context, scopeName string) error
	DeleteAllRefreshTokens(ctx context.Context, userID string) error
	DeleteInternalClient(ctx context.Context, clientID string) error
	DeleteRefreshToken(ctx context.Context, arg DeleteRefreshTokenParams) error
	DeleteTenant(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	GetClientScopes(ctx context.Context, clientID string) ([]GetClientScopesRow, error)
	GetClientStatistics(ctx context.Context, arg GetClientStatisticsParams) (GetClientStatisticsRow, error)
	GetInternalClient(ctx context.Context, clientID string) (InternalClient, error)
	GetInternalClientByID(ctx context.Context, clientID string) (InternalClient, error)
	GetRefreshToken(ctx context.Context, arg GetRefreshTokenParams) (UserRefreshToken, error)
	GetScopeByName(ctx context.Context, scopeName string) (Scope, error)
	GetServiceAccessLogs(ctx context.Context, arg GetServiceAccessLogsParams) ([]ServiceAccessLog, error)
	GetServiceToken(ctx context.Context, tokenHash string) (ServiceToken, error)
	GetTenantByID(ctx context.Context, id string) (Tenant, error)
	GetTenantByPublicKey(ctx context.Context, apiPublicKey string) (Tenant, error)
	GetTenantBySecretKeyHash(ctx context.Context, apiSecretKeyHash string) (Tenant, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserCountByTenant(ctx context.Context, tenantID string) (int64, error)
	GetUsersByTenant(ctx context.Context, tenantID string) ([]User, error)
	GrantScopeToClient(ctx context.Context, arg GrantScopeToClientParams) error
	ListAllScopes(ctx context.Context) ([]Scope, error)
	ListInternalClients(ctx context.Context) ([]InternalClient, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	LogServiceAccess(ctx context.Context, arg LogServiceAccessParams) error
	RevokeScopeFromClient(ctx context.Context, arg RevokeScopeFromClientParams) error
	RevokeServiceToken(ctx context.Context, tokenHash string) error
	StoreServiceToken(ctx context.Context, arg StoreServiceTokenParams) error
	UpdateInternalClient(ctx context.Context, arg UpdateInternalClientParams) (InternalClient, error)
	UpdateScope(ctx context.Context, arg UpdateScopeParams) (Scope, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
